import {readFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

export interface ComponentDoc {
  name: string
  description: string
  importPath: string
  polymorphic: boolean
  defaultElement: string | null
  clientComponent: boolean
  storyUrl: string
}

export interface McpData {
  generatedAt: string
  package: string
  components: ComponentDoc[]
}

/** Loads the doc data generated by `npm run generate:llms` (scripts/generate-llms.mjs). */
export function loadMcpData(): McpData {
  const raw = readFileSync(join(root, 'data/mcp-data.json'), 'utf8')
  return JSON.parse(raw) as McpData
}

/** One-line-per-component summary, cheapest way to see what's available. */
export function listComponents(data: McpData) {
  return data.components.map((c) => ({
    name: c.name,
    description: c.description.split('\n')[0] ?? ''
  }))
}

/** Full doc for a single named component, case-insensitive. */
export function getComponentDoc(
  data: McpData,
  name: string
): ComponentDoc | null {
  return (
    data.components.find((c) => c.name.toLowerCase() === name.toLowerCase()) ??
    null
  )
}

export interface SearchResult {
  component: string
  snippet: string
}

/**
 * Naive keyword search across component docs and the full llms-full.txt
 * reference. Deliberately simple (substring match, no fuzziness/embeddings)
 * — appropriate for a library with a handful of components; revisit if
 * that stops being true.
 */
export function searchDocs(
  data: McpData,
  llmsFullText: string,
  query: string
): SearchResult[] {
  const needle = query.trim().toLowerCase()
  if (!needle) return []

  const results: SearchResult[] = []

  for (const component of data.components) {
    const haystack = `${component.name}\n${component.description}`.toLowerCase()
    if (haystack.includes(needle)) {
      results.push({component: component.name, snippet: component.description})
    }
  }

  const sections = llmsFullText.split(/\n(?=## )/)
  for (const section of sections) {
    if (section.toLowerCase().includes(needle)) {
      const heading =
        section.split('\n')[0]?.replace(/^#+\s*/, '') ?? 'Reference'
      if (!results.some((r) => r.component === heading)) {
        results.push({
          component: heading,
          snippet: section.trim().slice(0, 500)
        })
      }
    }
  }

  return results
}
